services:
  test_app:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
      target: tester
    image: ghcr.io/approvers/imperial-household-agency:test-${GIT_SHA:-latest}
    container_name: imperial-household-agency-test
    # TODO: Change here to start a bot process!
    command: ["python", "-m", "pytest", "--cov-report=xml"]
    tty: true
    depends_on:
      test_db:
        condition: service_healthy
    restart: "no"
    env_file:
      - "./env/test.env"
    volumes:
      - "./env/test.env:/opt/app/env/test.env"

  test_db:
    build:
      context: ./docker/postgresql
      dockerfile: Dockerfile
    container_name: imperial-household-agency-test-db
    env_file:
      - "./env/test.env"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test_user -d test_huggingface_lb" ]
      interval: 1s
      timeout: 3s
      retries: 30
    stop_grace_period: 1s
