services:
  developer_app:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
      target: developer
    image: imperial-household-agency
    container_name: app
    # TODO: Change here to start a bot process!
    command: ["sleep", "infinity"]
    tty: true
    depends_on:
      - developer_db
    env_file:
      - "./env/local.env"
    volumes:
      - "./env/local.env:/opt/app/env/local.env"
    develop:
      watch:
        - action: sync
          path: .
          target: /opt/app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./uv.lock

  developer_db:
    build:
      context: ./docker/postgresql
      dockerfile: Dockerfile
    container_name: db
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - developer_db_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  developer_db_data:
