"""create initial tables

Revision ID: 87e1bd665ac8
Revises: 
Create Date: 2026-01-04 17:05:57.842666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import src

# revision identifiers, used by Alembic.
revision: str = '87e1bd665ac8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messenger',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('record_id', src.system.infrastructure.repository.sqlalchemy.type.ulid.ULIDColumn(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('user',
    sa.Column('messenger_record_id', src.system.infrastructure.repository.sqlalchemy.type.ulid.ULIDColumn(length=26), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('record_id', src.system.infrastructure.repository.sqlalchemy.type.ulid.ULIDColumn(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['messenger_record_id'], ['messenger.record_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id'),
    sa.UniqueConstraint('messenger_record_id', 'user_id')
    )
    op.create_table('nickname_changelog',
    sa.Column('user_record_id', src.system.infrastructure.repository.sqlalchemy.type.ulid.ULIDColumn(length=26), nullable=False),
    sa.Column('before', sa.String(), nullable=True),
    sa.Column('after', sa.String(), nullable=False),
    sa.Column('record_id', src.system.infrastructure.repository.sqlalchemy.type.ulid.ULIDColumn(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_record_id'], ['user.record_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nickname_changelog')
    op.drop_table('user')
    op.drop_table('messenger')
    # ### end Alembic commands ###
