name: CI on Push

"on":
  push:
    branches:
      - '**'

env:
  REGISTRY: ghcr.io
  BUILD_TARGET: "developer"
  IMAGE_NAME_BASE: ${{ github.repository }}
  IMAGE_NAME_SUFFIX: "-developer"
  IMAGE_NAME_FULL: ${{ github.repository }}${{ env.IMAGE_NAME_SUFFIX }}

jobs:
  build:
    name: Build Debug Image
    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/template-build-and-push.yml
    with:
      build_target: ${{ env.BUILD_TARGET }}
      image_name_base: ${{ env.IMAGE_NAME_BASE }}
      image_name_suffix: ${{ env.IMAGE_NAME_SUFFIX }}
      tags: ''

  lint:
    name: Lint inside Container
    needs: build
    permissions:
      contents: read
      packages: read

    uses: ./.github/workflows/template-python-ci.yml
    with:
      image_name_full: ${{ env.IMAGE_NAME_FULL }}
